import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderTop from "../Components/HeaderTop";
import HeaderMain from "../Components/HeaderMain";
import Navbar from "../Components/Navbar";
import "slick-carousel/slick/slick.css";
import type { AppProps } from "next/app";
import { ThemeProvider } from "next-themes";
import "slick-carousel/slick/slick-theme.css";
import MobNavebar from "../Components/MobNavebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ShOpNow Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop />
        <HeaderMain />
        <Navbar />
        <MobNavebar />

        {children}
      </body>
    </html>
  );
}
